# Generated by Django 4.2.6 on 2024-01-12 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, default='', max_length=3000, null=True)),
                ('invoice_number', models.IntegerField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Customer Name')),
                ('line_one', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 1')),
                ('line_one_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_one_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)')),
                ('line_one_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('line_two', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 2')),
                ('line_two_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_two_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)')),
                ('line_two_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('line_three', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 3')),
                ('line_three_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_three_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)')),
                ('line_three_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('line_four', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 4')),
                ('line_four_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_four_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)')),
                ('line_four_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('line_five', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 5')),
                ('line_five_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_five_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)')),
                ('line_five_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('line_six', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 6')),
                ('line_six_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_six_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)')),
                ('line_six_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('line_seven', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 7')),
                ('line_seven_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_seven_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)')),
                ('line_seven_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('line_eight', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 8')),
                ('line_eight_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_eight_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)')),
                ('line_eight_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('line_nine', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 9')),
                ('line_nine_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_nine_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)')),
                ('line_nine_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('line_ten', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 10')),
                ('line_ten_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_ten_unit_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price (D)')),
                ('line_ten_total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total (D)')),
                ('phone_number', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('total_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('balance', models.IntegerField(blank=True, default='0', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('invoice_type', models.CharField(blank=True, choices=[('Invoice', 'Invoice'), ('Receipt', 'Receipt')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_to', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_to', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category')),
            ],
        ),
    ]
